### ISSUE TITLE
Please update petlink on pypi

### ISSUE THREAD

**Issue by sanjayankur31** [spedemon/petlink#1]
Hello,

I was looking at [petlink on pypi](https://pypi.org/project/petlink/) to include it in [NeuroFedora](https://pagure.io/neuro-sig/NeuroFedora/issue/13). The link to upstream there does not work any more, and while the version on pypi is 0.3.1, the setup.py file here says 0.3.0. Would it be possible to sync these up?

Also, given that the last commit was a few years ago, is petlink still usable with py3 and so on?

Thanks,
Ankur

**Comment by spedemon** [comment]
Hello Ankur, 

Thank you for your help!! I have updated the projects - [petlink on github](https://github.com/spedemon/petlink) and [petlink on pypi](https://pypi.org/project/petlink/) to v3.2, which is now compatible with Python3. 

Stefano

**Comment by sanjayankur31** [comment]
Thank you very much!
